version: '3.4'

services:
  webknossos-connect:
    build:
      context: .
      target: prod
    image: scalableminds/webknossos-connect:${DOCKER_TAG:-master}
    volumes:
      - ./data:/${CI:-app/data}
    network_mode: host
    environment:
      - TZ=${TZ:-Europe/Berlin}

  dev:
    build:
      context: .
      target: dev
    image: scalableminds/webknossos-connect-dev:${DOCKER_TAG:-master}
    volumes:
      - ./wkconnect:/app/wkconnect
      - ./data:/app/data
    network_mode: host
    environment:
      - TZ=${TZ:-Europe/Berlin}
    cap_add:
      - SYS_PTRACE
