version: 2
jobs:
  static_checks:
    docker:
      - image: python:3.7.2
    environment:
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: pip install --user --upgrade pipenv
      - restore_cache:
          name: Restore pipenv cache
          keys:
            - pipenv-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - pipenv-cache-{{ checksum ".circleci/cache_version" }}-master
      - run:
          name: Install packages
          command: pipenv sync --dev
      - run:
          name: Lint
          command: pipenv run lint
      - run:
          name: Check pretty
          command: pipenv run pretty-check
      - restore_cache:
          name: Restore mypy cache
          keys:
            - mypy-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - mypy-cache-{{ checksum ".circleci/cache_version" }}-master
      - run:
          name: Check typing
          command: pipenv run type-check
      - save_cache:
          name: Save pipenv cache
          key: pipenv-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.cache/pipenv"
      - save_cache:
          name: Save mypy cache
          key: mypy-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".mypy_cache"

workflows:
  version: 2
  default:
    jobs:
      - static_checks
