version: 2
jobs:
  static_checks_push:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout

      - run:
          name: Install poetry
          command: pip install poetry==1.0.0b4 && poetry config virtualenvs.create false

      - run:
          name: Install packages
          command: poetry install
      - run:
          name: Lint
          command: scripts/lint.sh
      - run:
          name: Check pretty
          command: scripts/pretty-check.sh
      - run:
          name: Check typing
          command: scripts/type-check.sh

      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose build webknossos-connect
      - run:
          name: Smoketest
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose up -d webknossos-connect
            name="$(docker-compose ps -q webknossos-connect)"
            sleep 20
            status="$(docker inspect --format='{{.State.Health.Status}}' $name)"
            [ "$status" = "healthy" ]
            docker-compose down
      - run:
          name: Push docker image
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker tag \
                scalableminds/webknossos-connect:${DOCKER_TAG} \
                scalableminds/webknossos-connect:${CIRCLE_BRANCH}
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker-compose push webknossos-connect
            docker push scalableminds/webknossos-connect:${CIRCLE_BRANCH}
            docker logout

workflows:
  version: 2
  circleci_build:
    jobs:
      - static_checks_push
