version: 2
jobs:
  static_checks_push:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          name: Restore pipenv cache
          keys:
            - pipenv-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - pipenv-cache-{{ checksum ".circleci/cache_version" }}-master
      - run:
          name: Install packages
          command: pipenv sync --dev
      - run:
          name: Lint
          command: pipenv run lint
      - run:
          name: Check pretty
          command: pipenv run pretty-check
      - restore_cache:
          name: Restore mypy cache
          keys:
            - mypy-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - mypy-cache-{{ checksum ".circleci/cache_version" }}-master
      - run:
          name: Check typing
          command: pipenv run type-check
      - save_cache:
          name: Save pipenv cache
          key: pipenv-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.cache/pipenv"
      - save_cache:
          name: Save mypy cache
          key: mypy-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".mypy_cache"
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose build webknossos-connect
      - run:
          name: Smoketest
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker-compose up -d webknossos-connect
            name="$(docker-compose ps -q webknossos-connect)"
            sleep 20
            status="$(docker inspect --format='{{.State.Health.Status}}' $name)"
            [ "$status" = "healthy" ]
            docker-compose down
      - run:
          name: Push docker image
          command: |
            export DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker tag \
                scalableminds/webknossos-connect:${DOCKER_TAG} \
                scalableminds/webknossos-connect:${CIRCLE_BRANCH}
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker-compose push webknossos-connect
            docker push scalableminds/webknossos-connect:${CIRCLE_BRANCH}
            docker logout

workflows:
  version: 2
  circleci_build:
    jobs:
      - static_checks_push
